#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-${script_dir}/../configs/deepspeed_zero3_cpu_offload.json}"
export MAX_JOBS="${MAX_JOBS:-4}"
export RAPO_SMOKE_PRECISION="${RAPO_SMOKE_PRECISION:-fp16}"
export RAPO_SMOKE_ATTN_IMPLEMENTATION="${RAPO_SMOKE_ATTN_IMPLEMENTATION:-sdpa}"
export RAPO_SMOKE_MAX_PROMPT_LENGTH="${RAPO_SMOKE_MAX_PROMPT_LENGTH:-512}"
export RAPO_SMOKE_MAX_COMPLETION_LENGTH="${RAPO_SMOKE_MAX_COMPLETION_LENGTH:-32}"
export RAPO_SMOKE_GRADIENT_ACCUMULATION_STEPS="${RAPO_SMOKE_GRADIENT_ACCUMULATION_STEPS:-2}"
export RAPO_SMOKE_GRADIENT_CHECKPOINTING="${RAPO_SMOKE_GRADIENT_CHECKPOINTING:-true}"
export RAPO_SMOKE_MAX_PIXELS="${RAPO_SMOKE_MAX_PIXELS:-100352}"
export RAPO_SMOKE_MIN_PIXELS="${RAPO_SMOKE_MIN_PIXELS:-3136}"
export RAPO_SMOKE_NUM_GENERATIONS="${RAPO_SMOKE_NUM_GENERATIONS:-2}"

exec bash "${script_dir}/run_imagenet_r_smoke.sh" "$@"
